### 1) EDA : size, info , shape 등
### 2) 전체 테이블 데이터자료 기준, 원하는 값(행,열)을 어떻게 찾아오고, 결측치는 어떻게 대체
### 3) 서로 다른 데이터를 어떻게 붙여서 사용할 것인가?

In [18]:
import pandas as pd

PATH = "csse_covid_19_data/csse_covid_19_daily_reports/"

doc = pd.read_csv(f"{PATH}04-01-2020.csv", encoding = "utf-8-sig")

In [2]:
doc.head()

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
0,45001.0,Abbeville,South Carolina,US,2020-04-01 21:58:49,34.223334,-82.461707,4,0,0,4,"Abbeville, South Carolina, US"
1,22001.0,Acadia,Louisiana,US,2020-04-01 21:58:49,30.295065,-92.414197,47,1,0,46,"Acadia, Louisiana, US"
2,51001.0,Accomack,Virginia,US,2020-04-01 21:58:49,37.767072,-75.632346,7,0,0,7,"Accomack, Virginia, US"
3,16001.0,Ada,Idaho,US,2020-04-01 21:58:49,43.452658,-116.241552,195,3,0,192,"Ada, Idaho, US"
4,19001.0,Adair,Iowa,US,2020-04-01 21:58:49,41.330756,-94.471059,1,0,0,1,"Adair, Iowa, US"

In [3]:
doc.shape

(2522, 12)

In [4]:
doc = doc.groupby("Country_Region").sum() # 그룹의 대상이 되면 반드시 인덱스의 요소로 이동한다
doc

,FIPS,Admin2,Province_State,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
Country_Region,,,,,,,,,,,
Afghanistan,0.0,0,0,2020-04-01 21:58:34,33.939110,67.709953,192,4,5,183,Afghanistan
Albania,0.0,0,0,2020-04-01 21:58:34,41.153300,20.168300,259,15,67,177,Albania
Algeria,0.0,0,0,2020-04-01 21:58:34,28.033900,1.659600,847,58,61,728,Algeria
Andorra,0.0,0,0,2020-04-01 21:58:34,42.506300,1.521800,390,14,10,366,Andorra
Angola,0.0,0,0,2020-04-01 21:58:34,-11.202700,17.873900,8,2,1,5,Angola
...,...,...,...,...,...,...,...,...,...,...,...
Vietnam,0.0,0,0,2020-04-01 21:58:34,14.058324,108.277199,218,0,63,155,Vietnam
West Bank and Gaza,0.0,0,0,2020-04-01 21:58:34,31.952200,35.233200,134,1,18,115,West Bank and Gaza
Winter Olympics 2022,0.0,0,0,2020-04-01 21:58:49,39.904200,116.407400,0,0,0,0,Winter Olympics 2022
Zambia,0.0,0,0,2020-04-01 21:58:34,-13.133897,27.849332,36,0,0,36,Zambia
Zimbabwe,0.0,0,0,2020-04-01 21:58:34,-19.015438,29.154857,8,1,0,7,Zimbabwe

In [5]:
doc.columns

Index(['FIPS', 'Admin2', 'Province_State', 'Last_Update', 'Lat', 'Long_',
       'Confirmed', 'Deaths', 'Recovered', 'Active', 'Combined_Key'],
      dtype='object')

In [6]:
doc.index

Index(['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola', 'Antarctica',
       'Antigua and Barbuda', 'Argentina', 'Armenia', 'Australia',
       ...
       'United Arab Emirates', 'United Kingdom', 'Uruguay', 'Uzbekistan',
       'Venezuela', 'Vietnam', 'West Bank and Gaza', 'Winter Olympics 2022',
       'Zambia', 'Zimbabwe'],
      dtype='object', name='Country_Region', length=190)

In [7]:
doc[doc.index == "US"]

,FIPS,Admin2,Province_State,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
Country_Region,,,,,,,,,,,
US,65168934.0,AbbevilleAcadiaAccomackAdaAdairAdairAdairAdams...,South CarolinaLouisianaVirginiaIdahoIowaMissou...,2020-04-01 21:58:492020-04-01 21:58:492020-04-...,82956.96013,-197553.963757,216936,5222,8474,209150,"Abbeville, South Carolina, USAcadia, Louisiana..."

##### 1) EDA : size, info, shape 등
##### 2) 전체 테이블 데이터 자료 기준, 원하는 값(행,열)을 어떻게 찾아오고, 결측치는 어떻게 대체
##### 3) 전체 테이블 내 특정 컬럼을 기준으로 그룹화하는 방법 & 그룹화된 상태에서 특정 조건에 해당되는 값만 조회
##### 4) 특정 컬럼 값 타입 변경

In [8]:
doc = pd.read_csv(f"{PATH}01-22-2020.csv", encoding = "utf-8-sig")

In [9]:
doc.head()

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,Anhui,Mainland China,1/22/2020 17:00,1.0,NaN,NaN
1,Beijing,Mainland China,1/22/2020 17:00,14.0,NaN,NaN
2,Chongqing,Mainland China,1/22/2020 17:00,6.0,NaN,NaN
3,Fujian,Mainland China,1/22/2020 17:00,1.0,NaN,NaN
4,Gansu,Mainland China,1/22/2020 17:00,NaN,NaN,NaN

In [10]:
doc = doc[["Country/Region","Confirmed"]]

In [11]:
doc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76 entries, 0 to 75
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country/Region  76 non-null     object
 1   Confirmed       66 non-null     float64
dtypes: float64(1), object(1)
memory usage: 1.3+ KB

In [12]:
# 데이터의 타입을 변경하고자 할 때, 우선적으로 결측치 값을 제거하고 시작 (결측치는 타입 변경 시 에러 발생)

doc = doc.dropna(subset = ["Confirmed"])
doc.info()

<class 'pandas.core.frame.DataFrame'>
Index: 66 entries, 0 to 75
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country/Region  66 non-null     object
 1   Confirmed       66 non-null     float64
dtypes: float64(1), object(1)
memory usage: 1.5+ KB

In [13]:
doc = doc.astype({"Confirmed" : "int64"}) # 특정 컬럼의 타입 변경 시, 사용하는 메서드
doc.info

<bound method DataFrame.info of     Country/Region  Confirmed
0   Mainland China          1
1   Mainland China         14
2   Mainland China          6
3   Mainland China          1
5   Mainland China         26
..             ...        ...
71  United Kingdom          0
72           Nauru          0
73     New Zealand          0
74          Tuvalu          0
75  United Kingdom          0

[66 rows x 2 columns]>

In [14]:
doc.head()

   Country/Region  Confirmed
0  Mainland China          1
1  Mainland China         14
2  Mainland China          6
3  Mainland China          1
5  Mainland China         26

In [15]:
doc.columns

Index(['Country/Region', 'Confirmed'], dtype='object')

In [16]:
doc.columns = ['Country_Region','Confirmed']

In [17]:
doc

    Country_Region  Confirmed
0   Mainland China          1
1   Mainland China         14
2   Mainland China          6
3   Mainland China          1
5   Mainland China         26
..             ...        ...
71  United Kingdom          0
72           Nauru          0
73     New Zealand          0
74          Tuvalu          0
75  United Kingdom          0

[66 rows x 2 columns]

##### 1) EDA : size, info, shape 등
##### 2) 전체 테이블 데이터 자료 기준, 원하는 값(행,열)을 어떻게 찾아오고, 결측치는 어떻게 대체
##### 3) 전체 테이블 내 특정 컬럼을 기준으로 그룹화하는 방법 & 그룹화된 상태에서 특정 조건에 해당되는 값만 조회
##### 4) 특정 컬럼 값 타입 변경
##### 5) 전체 테이블 내 중복 행 확인/제거

In [20]:
PATH = "csse_covid_19_data/"

doc = pd.read_csv(f"{PATH}UID_ISO_FIPS_LookUp_Table.csv", encoding = "utf-8-sig")

In [21]:
doc.head()

,UID,iso2,iso3,code3,FIPS,Admin2,Province_State,Country_Region,Lat,Long_,Combined_Key,Population
0,4,AF,AFG,4.0,NaN,NaN,NaN,Afghanistan,33.93911,67.709953,Afghanistan,38928341.0
1,8,AL,ALB,8.0,NaN,NaN,NaN,Albania,41.15330,20.168300,Albania,2877800.0
2,10,AQ,ATA,10.0,NaN,NaN,NaN,Antarctica,-71.94990,23.347000,Antarctica,NaN
3,12,DZ,DZA,12.0,NaN,NaN,NaN,Algeria,28.03390,1.659600,Algeria,43851043.0
4,20,AD,AND,20.0,NaN,NaN,NaN,Andorra,42.50630,1.521800,Andorra,77265.0

In [22]:
doc = doc[["iso2", "Country_Region"]]

In [23]:
doc.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
4316     True
4317     True
4318     True
4319     True
4320     True
Length: 4321, dtype: bool

In [24]:
doc[doc.duplicated()]

     iso2 Country_Region
17     BE        Belgium
18     BE        Belgium
19     BE        Belgium
20     BE        Belgium
21     BE        Belgium
...   ...            ...
4316   US             US
4317   US             US
4318   US             US
4319   US             US
4320   US             US

[4080 rows x 2 columns]

In [27]:
# 중복되고 있는 값을 제거 => 2가지 선택지 : 첫번째 최초로 발견된 값을 살리고, 나머지를 제거
# 마지막으로 사용된 값만 살리고, 그 앞에서 사용된 값들을 제거

doc = doc.drop_duplicates(subset = "Country_Region", keep = "last") # 만약 keep x => firest
doc # 4080개 행 -> 202개 행

     iso2 Country_Region
0      AF    Afghanistan
1      AL        Albania
2      AQ     Antarctica
3      DZ        Algeria
4      AD        Andorra
...   ...            ...
853    ZW       Zimbabwe
862    AU      Australia
879    CA         Canada
914    MO          China
4320   US             US

[202 rows x 2 columns]